apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: rag2-oct17-3
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/maysunfaisal/rag2-oct17-3:8ea964cb90b7cf54de31351a5ec57bc376131380@sha256:fbd26724c98a6608390fbea31844a5f51b71fea5c95a801e288d2922d4326633 # use pre-built to bootstrap 
          name: app-inference
